
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plzgfbydqknqgjqbiuxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsemdmYnlkcWtucWdqcWJpdXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTQ4NzgsImV4cCI6MjA1NjQ5MDg3OH0.msj64SoiHJqCr4SdRVjEUQMKBXAQKub_eToKl2157aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use 'any' temporarily to bypass type issues while the database schema is being updated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
